### ISSUE TITLE
AndroidStudio编译失败

### ISSUE THREAD

**Issue by WestbrookZero** [luckyer/ros_android#1]
Could not find any version that matches org.ros.rosjava_bootstrap:gradle_plugins:[0.2,0.3).
Search in build.gradle files
你好，麻烦问一下，在AndroidStudio编译报错如下该怎么解决？

**Comment by luckyer** [comment]
如果你要用rosjava的话直接用rosjava_core的工程吧，我这个是参照http://wiki.ros.org/android_ndk/Tutorials/WrappingNativeRosjavaNode 做的，不是在AndroidStudio上使用的， 目前ros 对于Android的支持不是很友好，目前我也只能使用这个方式在Android上实现ros的功能

**Comment by WestbrookZero** [comment]
那请问你的这个工程有Android的绘制地图功能吗？

**Comment by luckyer** [comment]
> 那请问你的这个工程有Android的绘制地图功能吗？
有的，我移植了gmapping过来，不过雷达的节点是需要自己更换的

**Comment by WestbrookZero** [comment]
请问一下，根据机器人在地图中的位置，设定地图中的目标点使得机器人按照目标点移动该怎么做？
